import React from 'react';
import { Link } from 'gatsby';
import Layout from '../components/layout';
import SEO from '../components/seo';

const SecondPage = () => (
  <Layout>
    <SEO title="About" />
    <h1>About</h1>
    <p>
      I created this example site to demonstrate that a Gatsby site with
      client-side routes dynamically generated by the <code>createPages</code>{' '}
      Node API (see <code>gatsby-node.js</code> for setup):
      <ul>
        <li>Is able to be deployed to Netlify without special configuration</li>
        <li>
          Is unable to be deployed to Zeit Now without special configuration
          (pages in <code>/pages </code>are fine, but client-only routes return
          a 404 /<code>FILE_NOT_FOUND</code> error)
        </li>
      </ul>
    </p>
    <p>
      If these assumptions are correct, the{' '}
      <span style={{ color: `green` }}>green </span>
      links in the nav bar should break on the config-less Zeit Now site.
    </p>

    <Link to="/">Go back to the homepage</Link>
  </Layout>
);

export default SecondPage;
